### ISSUE TITLE
How to get input SVs format?

### ISSUE THREAD

**Issue by Chenglin20170390** [malonge/CallIntrogressions#1]
Hi, I would like to use your python script at 100 tomato article to infer introgressions.  However, I don't know how you get your final SVs file. Can you tell me that? 
   For me, I used sniffles to call individual SV, and then call population SV with survivor[](https://github.com/fritzsedlazeck/Sniffles/wiki/SV-calling-for-a-population), then I used population SVs (single file) and your script (get_distances.py) for introgressions. However, the result almost  1 in my Jaccard analysis. 

    I also try the methods of [100 tomato SVs](https://doi.org/10.1016/j.cell.2020.05.021)，sniffles to call individual SV, and merge with jasmine, However, after merging, I get only one sample merge file, but I input many samples. Can you explain it?  I have a bit confusing.

   Last, the most important, can you tell me the **format and methods of SVs** that you used in the Jaccard analysis? Many thanks

**Comment by malonge** [comment]
Hi there,

To start with your last question, I don't follow your question exactly, but all the information needed is available in the STAR methods of the paper: https://doi.org/10.1016/j.cell.2020.05.021

As for SV merging, either SURVIVOR or Jasmine will work. All this script needs is for each line in the VCF file to have the `SUPP_VEC` field, which is a binary array indicating presence/absence of the SV in each of the samples. The samples should be listed in the final VCF comment line as is consistent with the VCF format.

Pllease read the usage message for additional info. For example, only one chromosome can be processed at a time. The input also requires a text file associating each sample with a taxonomic group (SLL, SLC, SP, GAL, and CHE).

One potential inconvenience is when I parse the VCF file to get the sample name here:

https://github.com/malonge/CallIntrogressions/blob/ea846358183328dbdcb95c5325ed778d4de05a14/get_distances.py#L83

In my VCF file, the samples were named `{accession}.ont.s.`, for example, `M82.ont.s`. So you may want to make a fork and change that line to match your own sample names, or else you can change the sample names to match what I had.

Thanks

**Comment by Chenglin20170390** [comment]
ok, many thanks, after add  `--output_genotypes`, I get the genotype file from Jasmine.
